### ISSUE TITLE
4.06.1 compatibility

### ISSUE THREAD

**Issue by jpdeplaix** [camlp5/camlp5#17]
I was trying to install camlp5.7.03 via opam on the latest OCaml version released today (4.06.1) and I ran into this error:
```
Sorry: the compatibility with ocaml version "4.06.1"
is not yet implemented. Please report.

Information: directory ocaml_stuff/4.06.1 is missing.

Configuration failed.
```

**Comment by jaapb** [comment]
As a workaround, doing
`cd ocaml_stuff && cp -r 4.06.0 4.06.1`
and
`cd ocaml_src/lib/versdep && cp 4.06.0.ml 4.06.1.ml`
seems to work for me.

**Comment by roglo** [comment]
Fixed in github. Release soon.
