### ISSUE TITLE
make uninstall can execute rm -rf /

### ISSUE THREAD

**Issue by thierry-martinez** [camlp5/camlp5#18]
`make uninstall` executes `rm -rf /` if it is executed just after `./configure` fails.

This happens for instance when I try to install the camlp5 opam package in a 4.06.1 switch: this version of OCaml is not ruled out by the `opam` file, so `opam` tries to install it, runs `./configure` and fails with the message:
```
Sorry: the compatibility with ocaml version "4.06.1"
is not yet implemented. Please report.
```
Then `opam` executes `make uninstall` which executes `rm -rf /`.

**Comment by roglo** [comment]
The real problem is the compatibility with ocaml. The "rm -rf /" is an opam issue after. Ok, I just updated camlp5 for compatibility with ocaml 4.06.1 and 4.06.2. Release of Camlp5 soon.

**Comment by thierry-martinez** [comment]
Now fixed ( https://github.com/camlp5/camlp5/commit/d5616932193a05d4cffeb46deda7c003f9e38aca ). Thanks! (See also https://github.com/ocaml/opam-repository/issues/11440 )

**Comment by varkor** [comment]
A significant portion of my hard drive was just wiped when I didn't notice this behaviour was occurring into several minutes after `make uninstall` was called transitively (https://github.com/ocaml/opam/issues/3231). You absolutely need to have more safeguards in place for this.

**Comment by varkor** [comment]
I want to also point out that if you ever have a bug as potentially catastrophic as this, it is absolutely your responsibility to make sure all your dependents have the fixed version **as soon as possible**.

**Comment by nerpderp83** [comment]
This just wiped out my home directory. See https://github.com/ocaml/opam/issues/3316

**Comment by roglo** [comment]
I am very confused, very sorry. But I can't do anything. I made a new release of Camlp5 (7.05) when I was notified of the problem. This error is also due to the way opam works, which should not do anything if configuration failed. Opam should be fixed too.
