### ISSUE TITLE
`nonrec` keyword for types

### ISSUE THREAD

**Issue by Kakadu** [camlp5/camlp5#20]
I spent some time trying to [support](https://github.com/Kakadu/camlp5/commit/5136aa1c9eb50e7b8cdeedb3e0de29df72e0d718) non-recursive type definitions in parser but not yet succeeded. I think I found right grammar entry to put `nonrec` flag into it bu in current state of thinks the piece of code `type nonrec t = int` is parsed the same as: 

    type nonrec
    let _ = (t = int)

Which obviously is not what I want. I should probably fix the order of rules, or treat `nonrec`  as a keyword and disallow it from type identifiers, or I don't know.... Can you give me a piece of advice, @roglo  ?

**Comment by roglo** [comment]
Changing the file ocaml_src/meta/pa_r.ml is not the good way. The files in subdirectories ocaml_src are pretty printed from the normal files, and are often difficult to manipulate. You should make your changes in meta/pa_r.ml.

**Comment by Kakadu** [comment]
@roglo Oh, it seems to be better now. Can you recommend a reading how to extend existing quotations/antiquotations? More precisesly, where should I fix to support ` <:str_item< type $_flag:nr$ $_list:tdl$ >>` ?

**Comment by roglo** [comment]
It has to be done in the file meta/q_MLast.ml. But this file can (and must) be created from the file meta/pa_r.ml. If you changed meta/pa_r.ml, you can see the possible changes that would appear in meta/q_MLast.ml by doing
`cd meta
make compare_q_MLast`
If you think the changes are ok, type
`make bootstrap_q_MLast`
which changes the file. Then do make and make bootstrap (perhaps several times up to the message telling it is bootstrapped appear).

Note you can do a syntax extension without having to change camlp5 sources. The aim of camlp5 is to be able to do that. Read the doc.

**Comment by Kakadu** [comment]
All of this looks like extremely complicated. Let me ask another question to clarify something.

Let's say I want to add extra boolean flag for `StTyp` constructor which will represent non-recursivity. There are to places for change: `/ocaml_src/main/mLast.mli` and `./main/mLast.mli`. I changed both and now I'm stuck on compilation of `meta/pa_r.ml` because of the code 

      | "type"; nr = V (FLAG "nonrec"); tdl = V (LIST1 type_decl SEP "and") ->
          <:str_item< type $_list:tdl$ >>
    
where quotation constructs `StTyp` of two arguments instead of three. What should I do next?

1. `/ocaml_src/meta/q_MLast.ml` seems to be generated so I shouldn't edit it
2. `/ocaml_src/meta/q_ast.ml` seems to be not auto generated  and may be the right place but I don't fully understand where should I edit it. Is module `Meta_make` what I want?
3. Maybe I should change something in `/meta/q_MLast.ml` and bootstrap something?

**Comment by roglo** [comment]
Actually, <:str_item< type $_list:tdl$ >> is syntactically equal to MLast.StTyp loc tdl (something like that). So, if you change the parameters of StTyp, temporarilly comment this quotation and write MLast.StTyp loc rfl tdl after
`(* <:str_item< type $_list:tdl >> *) MLast.StTyp loc rfl tdl`

Then make boot, and make coreboot up to it works. Then cd meta, do make compare_MLast and make bootstrap_MLast. Then cd .., make boot and make coreboot to check it works. Then remove your MLast.StTyp loc rfl tdl , uncomment the quotation and add your flag <:str_item< type $_flag:rfl$ $_list:tdl$ >>.

I always do that in these circumstances.

**Comment by Kakadu** [comment]
@roglo After manipulations that you recommended `make` command finishes successfully and minor testing says that demo sources with `nonrec` are parsed and printed right. But after `make clean` I can't compile again because the same error in `meta/pa_r.ml`. Any advice?

I [pushed](https://github.com/Kakadu/camlp5/commit/925216cc9ff3df32387f59146c0e6bca57300766) the current state of my patch, if you are interested.

**Comment by roglo** [comment]
After your changes, and before make clean, you have to bootstrap sources. Since you already do make clean, save your changes somewhere, return to the initial state, compile again. Now, redo your changes, up to a successful make bootstrap, don't make clean and do the following:
`make compare_sources | less`
to control the changes you have done that would be done in ocaml_src directories. And then
`make bootstrap_sources`
Then, you can do make clean.

**Comment by Kakadu** [comment]
We should close this. @roglo Do you think that it is worth to convert our QA session into tutorial about contributing?

**Comment by roglo** [comment]
There is a documentation here https://camlp5.github.io/doc/htmlc/sources.html but if you think it should be completed, fixed, etc. you can do it : in camlp5 sources, go to directory doc/htmlp, edit the html file(s) you want to change (here, it would be sources.html). In that directory you can do `make` to create the final html files in `../html`, `make ps` to make a postscript version, `make pdf` to make a pdf version, `make info` to make an 'info' version. The basic version *is* the html version! (I know it is rarely a usage, but I did it like that).
