### ISSUE TITLE
Is it possible to revert the effect of an `Entry.create`?

### ISSUE THREAD

**Issue by herbelin** [camlp5/camlp5#21]
Hi @roglo,

Would it make sense / be possible to provide some `Entry.delete` which reverts the effect of a `Entry.create` (assuming that the entry has no more rules declared for it).

[J'essaie d'implémenter le backtrack pour la nouvelle commande `Declare Custom Entry` de Coq (PR coq/coq#6247) et je voudrais pouvoir annuler le `Entry.create` exécuté par la commande Coq. Serait-ce facile à implémenter côté camlp5 ?]

**Comment by roglo** [comment]
C'est juste une variable : si personne ne la référence, elle est supprimée par le garbage collector.

**Comment by herbelin** [comment]
> C'est juste une variable : si personne ne la référence, elle est supprimée par le garbage collector.

C'est effectivement une approche possible, que nous suivons pour d'autres types d'objets en Coq.

Actuellement, pour le backtrack, nous utilisons `delete_rule` pour défaire l'ajout de règles. Nous pourrions probablement commuter vers un mode basé uniquement sur des références ocaml automatiquement collectées si nous avions un accès à l'état global du parseur, ou même à l'état global de chaque entrée (même si le type de ces états était abstrait).

Est-ce qu'il y a un moyen de faire cela actuellement, i.e. un moyen de sauver/restaurer l'état du parseur ou de ses entrées ?

**Comment by roglo** [comment]
Bin euh... je ne pense pas. L'extension de grammaires est un effet de bord. Il faut défaire ce qu'on a fait.
