### ISSUE TITLE
Please support 4.07.0+rc1

### ISSUE THREAD

**Issue by ejgallego** [camlp5/camlp5#22]
OCaml 4.07.0 is around the corner, please add support for that release so downstream users can test it.

Merci!

**Comment by ejgallego** [comment]
https://sympa.inria.fr/sympa/arc/caml-list/2018-06/msg00032.html

**Comment by ejgallego** [comment]
@roglo , est-ce que tu penses faire un nouveau release bientôt ?

**Comment by roglo** [comment]
J'y travaille, mais comme j'ai inclus aussi une extension de @ppedrot, y a Coq qui ne compile plus. Faut qu'il me dise ce que je dois faire.
