### ISSUE TITLE
not compatible with 4.07.1

### ISSUE THREAD

**Issue by pmetzger** [camlp5/camlp5#28]
I get the following error trying to build the latest with 4.07.1:

```
Sorry: the compatibility with ocaml version "4.07.1"
is not yet implemented. Please report.

Information: directory ocaml_stuff/4.07.1 is missing.
```

**Comment by roglo** [comment]
With the latest github version of with the latest release?

**Comment by pmetzger** [comment]
This is with the July 4 release on the RELEASES tab, which is the latest one visible. I'm the maintainer of the MacPorts package for both OCaml and several related packages like camlp4 and camlp5 and this has prevented updating camlp5.

**Comment by pmetzger** [comment]
I believe this can now be closed.
