### ISSUE TITLE
Make camlp5 opam pin friendly

### ISSUE THREAD

**Issue by Kakadu** [camlp5/camlp5#3]
We need to put `opam` file in the root of the repository to make workflows with `opam pin add camlp5 https://github.com/camlp5/camlp5.git` work correctly. At the moment it grabs opam file from the main recipe repository and we basically have new sources with old recipe which makes new sources not installable (compiler version constraint).

**Comment by roglo** [comment]
Sorry, I don't use opam. If someone can build the required files for that, I can include them in Camlp5 distribution, but I am not going to do it.

**Comment by yakobowski** [comment]
On a related note, it would also be great to _upload_ an Opam package for Camlp5 6.17.

**Comment by roglo** [comment]
I repeat that I don't know how to do that. I am not going to do it. If you want to, please tell me what I have to do. Thank you.

**Comment by yakobowski** [comment]
I understand that. I'm not much more Opam-savvy myself, so my message was more geared towards the people who uploaded the previous versions of the Camlp5 packages (@mjustus and @gasche, apparently).

**Comment by gasche** [comment]
I am willing to push the opam package this time, but it is really simple and it would be better if the maintainer ( @roglo ) took care of it directly.

The steps I take are as follows:

- have a local clone of https://github.com/ocaml/opam-repository with an up-to-date master branch
- create a branch for a future pull request with the name.version of the new package, here `camlp5.6.17`
- go to `packages/camlp5`, copy the content of the last version's package directory into a new `camlp5.6.17` directory; `cd caml5.6.17`
- edit the files as appropriate; you need to check the `opam` files for changes (eg. maybe OCaml version constraints), and you need to change the `url` file -- to get the checksum of the new archive I download it locally with `wget`, and compute the checksum using the `md5sum` program.

**Comment by yakobowski** [comment]
Thanks Gabriel.

**Comment by gasche** [comment]
I think there is a meta-point that some of this could possibly be better documented. In this particular case I think that OPAM's [Packaging](https://opam.ocaml.org/doc/Packaging.html) documentation is not too bad, although maybe a bit too dense.

**Comment by hgouraud** [comment]
My current "repository" says    `0 [http]     default     https://opam.ocaml.org`
Should it rather point to `https://github.com/ocaml/opam-repository`

At the present time (for me), opam still says that:
`[ERROR] camlp5 is not available because your system doesn't comply with ocaml-version >= "1.07" & ocaml-version <= "4.03.0".`

Cheers,
Henri

**Comment by a2line** [comment]
camlp5 6.17 is now in https://github.com/ocaml/opam-repository/commit/49e6816cfee66daf48768202f62074760b6ac56b thanks to Henri!

**Comment by ejgallego** [comment]
How should we ensure this information is automatically updated? Should we close this issue with #12 ?
