### ISSUE TITLE
missing comment from pr_o

### ISSUE THREAD

**Issue by houndofsound** [camlp5/camlp5#30]
hello

the following demonstrates a particular position for a comment that does not get passed through:
let f()=
  let g()=1 in
  (*a disappearing comment*)
  ()

camlp5o pr_o.cmo <file>
the comment comes through with pr_r !

**Comment by houndofsound** [comment]
(disappearing comment)  ==> (*disppearing comment*)

**Comment by houndofsound** [comment]
(\*a disappearing comment\*)

**Comment by roglo** [comment]
Fixed. Thanks for the report.
