### ISSUE TITLE
Doc bug and question...

### ISSUE THREAD

**Issue by houndofsound** [camlp5/camlp5#31]
hello,

I'm having some trouble with the DELETE rule.

I have successfully introduced a new rule then immediately deleted it to verify all is well
but when I try to delete an existing rule:

#load "pa_extend.cmo";
#load "q_MLast.cmo";
#load "pa_macro.cmo";

open Pcaml;

Pcaml.syntax_name.val := "QCaml";
Pcaml.no_constructors_arity.val := True;

DELETE_RULE str_item: "let" END;

........
I get Not_found.
perhaps because there are multiple 'let' rules?
I tried adding an extra symbol "FLAG" then "rec" but it
fails:
Parse error: 'END' expected after [delete_rule_body] (in [expr])
feels like it will not accept anything...
--->OK, I see from the etc/... sources an example that show's a ';' separator.
---> but this is not what the docs say in '8.4 The DELETE_RULE statement'.

when it works as intended how do I specify extra symbols to target this rule:
      [ "let"; r = V (FLAG "rec"); l = V (LIST1 let_binding SEP "and") ->

and when the other is longer:
      [ "let"; r = V (FLAG "rec"); l = V (LIST1 let_binding SEP "and"); "in"; x = expr ->

how should they be differentiated?

**Comment by houndofsound** [comment]
on the 'Not_found' issue I can now see from a simpler example that all the tokens of a rule must be
matched - a unique prefix is not enough. 

but this begs the question as to how to match a token defined thusly:  'V(LIST1 let_binding SEP "and")'
when I attempted this literal the error was 'functional value' .... so one cannot match this token
definition as is.

**Comment by chetmurthy** [comment]
Hi, I don't know if you're interested in this issue. In case you are, I think that *fundamentally* there is no way to deal with DELETE RULE in the generality you're looking for, with the current design.  Perhaps what's needed is the ability to "name" rules, and then you could delete a rule by name.  But that also will require some deep surgery, I think.

I will confess that I still haven't dug deeply into Camlp5's grammar-interpreter machinery, and so, unless there's a really important bug, I would be loath to try to modify it.

Also though, I think that DELETE RULE is something to be avoided, generally.  Historically, caml-light was a batch system (in contrast to SML/NJ, for example) and it has always strived to be a batch system.  The only reasonable use of DELETE RULE is in an interactive toplevel, and .... well, there's lots of things that will not work well in an interactive toplevel, not just Camlp5.

I'm going to close this; if you want to discuss further, please feel free to reopen, and I'd be happy to try to help you solve the problem that causes you to want DELETE RULE functionality.
