### ISSUE TITLE
feature request:  ability to check existence of whitespace between tokens.

### ISSUE THREAD

**Issue by houndofsound** [camlp5/camlp5#32]
hello again,

I have been looking at how to eliminate the a.(0) array syntax in favour of the 'normal' one, a[0].
as this is a move away from applicative syntax I need to draw a distinction between
'f[]'  and 'f []' ie. presence of whitespace.
I see that Plexing.tok_comm is where comments are stored and that there probably is no current way to 
decide generally whether whitespace exists between tokens.
would it be appropriate to add a tok_whitespace: bool  field to handle this?
but then there is still a problem: the lexer tok_* values I think are not accessible from within the rules or
stream parsers one can write, no?

**Comment by chetmurthy** [comment]
Two thoughts:

(1) it is rare to find languages that are whitespace-sensitive.  The only one I can think of is Python, and that's quite controversial even to this day.  And even there, it's only whitespace at the beginning of a line, not interstitial whitespace.

(2) It would be a significant change, to allow "significant whitespace", and then to end up using it only for one case.

(3) Here's a thought: maybe you could change the syntax for lists?  Then you could reuse that "[]" syntax for array-arguments ?

(4) For sure, if you're serious about this, I think you might want to think carefully about how to sell more than just the Ocaml community: this is a pretty basic change, and one thing we've learned in the last 25 years is that syntax matters a lot more than people think, that breaking changes in syntax have deep and long-lasting repercussions, often unforeseen.

**Comment by chetmurthy** [comment]
Not doable.  closing.
