### ISSUE TITLE
GADTs are not supported?

### ISSUE THREAD

**Issue by Kakadu** [camlp5/camlp5#35]
I'm constructing an AST with GADT declarations and by some reason I can't print this AST into compiler's AST because of message `Failure: no generalized data types in this ocaml version`. Printing with `pr_o.cmo` works as expected.

I digged up a little bit and it seems that issue nearby https://github.com/camlp5/camlp5/blob/master/ocaml_src/lib/versdep/4.07.1.ml#L173 . We raise `Exit` if the last type that distinguish GADTs is specified (`<> None`). It should be fixable without a lot of effort. But before trying to fix this may I ask: do I understand situation right?

```ocaml
let ocaml_ptype_variant ctl priv =
  try
    let ctl =
      List.map
        (fun (c, tl, rto, loc) ->
           if rto <> None then raise Exit
           else
             let tl = Pcstr_tuple tl in
             {pcd_name = mkloc loc c; pcd_args = tl; pcd_res = None;
              pcd_loc = loc; pcd_attributes = []})
        ctl
    in
    Some (Ptype_variant ctl)
with Exit -> None
```

**Comment by chetmurthy** [comment]
Hi, I don't know a lot about GADTs in Ocaml, but I've been working to fix various version-related issues in camlp5: are you still interested in this problem?  If so, I'd be happy to look into fixing it, if you could provide some examples that don't work.  Also, if those examples worked correctly (parsing->printing) in ocamlformat, that would be helpful.

**Comment by Kakadu** [comment]
@chetmurthy  I personally not very interested in camlp5 but folks around me are (they are not very active online though). AFAIR any example with GADT can't be `pr_dump`ed. 

````
➜  ~ camlp5o gadt.ml 
File "gadt.ml", line 5, characters 5-91:
Failure: no generalized data types in this ocaml version
➜  ~ camlp5o pr_o.cmo gadt.ml
  type 'a s = S  (* abstract type will not work *)
  type z

  type ('a, 'size) vector =
    VNil : ('a, z) vector
  | VCons : 'a * ('a, 'size) vector -> ('a, 'size s) vector

➜  ~ cat gadt.ml 
  type 'a s = S  (* abstract type will not work *)
  type z

  type ('a, 'size) vector =
    | VNil  : ('a, z) vector
    | VCons : 'a * ('a, 'size) vector -> ('a, 'size s) vector
```

**Comment by chetmurthy** [comment]
Excellent.  That's a good start (small example).  I'll start having a look.

**Comment by Kakadu** [comment]
@chetmurthy I hope that link from the first post will be useful

**Comment by chetmurthy** [comment]
GADTs -should- work now.  I don't use them myself, but I think I have enough unit-tests to cover the syntax. closing.  reopen if you find bugs.
