### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by XVilka** [camlp5/camlp5#38]
There is a pull request to [port Campl5 to 4.08](https://github.com/camlp5/camlp5/pull/37) OCaml version. But seems like Camlp5 project is abandoned like Camlp4, there is no response for more than a week already, no response for a few months to [another PR](https://github.com/camlp5/camlp5/pull/34), and [last commit](https://github.com/camlp5/camlp5/commit/d64bafc13351c430e703e05a329fac0a1da44753) was a half a year ago. Does this mean the project is dead as Campl4?

See also https://discuss.ocaml.org/t/camlp5-and-ocaml-4-08/3985

**Comment by roglo** [comment]
Not dead but lazy. Ok, I have a look soon.

**Comment by XVilka** [comment]
@roglo thanks! Closing as solved haha.
