### ISSUE TITLE
Build fail, file plexing.ml, line 90, characters 26-31

### ISSUE THREAD

**Issue by Hibou57** [camlp5/camlp5#4]
Building Camlp5 6.17 with Ocaml 4.04.0 on Ubuntu 14.04 32 bits, I got this error during `make`:

    ocamlc.opt -warn-error A -I ../../ocaml_stuff/4.04.0/parsing -c -impl plexing.ppo
    File "plexing.ml", line 90, characters 26-31:
    Error: This expression has type bytes but an expression was expected of type
             string

**Comment by roglo** [comment]
Sorry, I don't have this problem while testing with ocaml 4.04.0. Are you sure that in camlp5 directory, you previously did: "make clean", then "./configure"?

**Comment by Hibou57** [comment]
I retried, and I’m invariably getting the same.

Using ocaml 4.04.0 and camlp5 rel617.

Ocaml configure options: `-flambda -safe-string`
Camlp5 configure options: `--strict`

Building Ocaml is OK, building Camlp5 with the just built Ocaml fails.

**Comment by roglo** [comment]
Ok, it was due to this option -safe-string, badly taken into account in camlp5. This is fixed. Could you confirm? Thank you.

**Comment by Hibou57** [comment]
Yes, confirmed, the fix solves the issue.

**Comment by roglo** [comment]
Ok, thank you.
