### ISSUE TITLE
Type-safe Grammar API not working case

### ISSUE THREAD

**Issue by roglo** [camlp5/camlp5#48]
#15 @ppedrot 
The example given in the documentation at  https://camlp5.github.io/doc/htmlc/grammars.html#a:Extensions-FOLD0-and-FOLD1 using "pa_extfold.cmo"

`#load "pa_extend.cmo";`
`#load "pa_extfold.cmo";`
`#load "q_MLast.cmo";`
`let loc = Ploc.dummy in`
`EXTEND`
`    Pcaml.expr:`
`      [ [ "sum";`
`          e =`
`            FOLD0 (fun e1 e2 -> <:expr< $e2$ + $e1$ >>) <:expr< 0 >>`
`              Pcaml.expr SEP ";";`
`          "end" -> e ] ]`
`    ;`
` END;`

does not compile any more. It says

> ocamlc -pp camlp5r -I `camlp5 -where` -c sum.ml 
> File "sum.ml", line 9, characters 10-97:
> Error: Unbound value Grammar.s_meta

**Comment by chetmurthy** [comment]
Closing this.  It is fixed in the 8.00 release-series.
