### ISSUE TITLE
[wish] support recent OCaml syntax for strings {|...|}

### ISSUE THREAD

**Issue by gares** [camlp5/camlp5#50]
As the title says, OCaml lets one write
```ocaml
let s = {delim|
  free text "using" string "delimiters" without quotes
|delim}
```

It would be nice to have that.

**Comment by chetmurthy** [comment]
Um, this should work with camlp5 ?  I submitted a patch that roglo@ merged a good while back?

**Comment by gares** [comment]
I'm using version 7.10, but I'm also using hol-light (that patches the lexer) so maybe the problem is there after all. Should version 7.10 contain your patch?

**Comment by chetmurthy** [comment]
Yes, here is the PR: https://github.com/camlp5/camlp5/pull/34

merged in the summer.
