### ISSUE TITLE
API change in 7.11?

### ISSUE THREAD

**Issue by Kakadu** [camlp5/camlp5#54]
I have a code that compiles with 4.10 but doesn't with 4.11. Is this API change intended? Why it is not mentioned in the https://github.com/camlp5/camlp5/blob/master/CHANGES file?

```ocaml
  let module_ ~loc name me =
    let lsme = [ (VaVal name, me)] in
    <:str_item< module $list:lsme$ >>
````
error message: new type is above, old one is below
````
       In module Str:
       Values do not match:
         val module_ : loc:loc -> string v option -> module_expr -> str_item
       is not included in
         val module_ : loc:loc -> string -> module_expr -> str_item
````

I found relevant commit but I don't know at the moment how to fix this error message properly
https://github.com/camlp5/camlp5/commit/92fbd096826d59b9cf78205a1c397752acb51c28

@chetmurthy

**Comment by chetmurthy** [comment]
Arrgh, my bad.  I should have documented this.  The reason for this change is that Ocaml 4.10 supports

module _ = struct end ;;

So to support this, in any location where there are module-names being bound, they can be "_", which maps to None.

But it should have been documented for sure.  Sorry, will get on it.

**Comment by Kakadu** [comment]
How should I fix this in client code? Any chance to rewrite my code in
backward compatible manner? Do we have a fancy quotation for something like
it?

**Comment by chetmurthy** [comment]
Is there some place I can have a look at and maybe compile your code?  I'd
like to understand how many things I broke 🙄 .... I'm new to maintaining
camlp5, so... mistakes....

**Comment by chetmurthy** [comment]
Multiple parts to this reply:

(1) how to work around (obviously unacceptable -- b/c it doesn't produce code that compiles under camlp5 710 and 711):
```
value module_ ~{loc} name me =
    let lsme = [ (VaVal (Some (VaVal name)), me)] in
    <:str_item< module $list:lsme$ >>
;
```
(2) ocaml 4.10 allows blank module-names in many locations (and previous versions did, too).  To support this required incompatible changes in the Camlp5 AST. In the case you cite, the type of "lsme" is `list (option (V string) * module_expr)` and you want it to be `list (string * module_expr)`.  There is no way of doing this that preserves Camlp5's quotations (that I can think of) and also has only a single AST type.

(3) So I could "pull forward" the old AST, along with the parser/pretty-printer/quotations, and write functions old-ast <-> new-ast (as ocaml is doing).  This isn't a panacea: lots of ocaml syntax isn't supported in that old AST and its associated parser/printer.  I'm currently working to get all of that up-to-date, and it would be infeasible to back-port that to the old AST unless there were really important applications that needed it. Then again, nobody's noticed that Camlp5 doesn't support all of modern Ocaml, so maybe it's OK?

(4) Also, one could IFDEF your client code to make it work under multiple versions of camlp5.  I would be happy to make these changes, if you give me access to your code -- just so you can see the changes and assess whether this would be acceptable.

Not an excuse -- just an explanation, in the hope that you'll think about it and let me know what you think would be most commodious for you.  Obviously I would prefer IFDEFs, but I can see why you might want the old version of the AST.

**Comment by Kakadu** [comment]
If you are sure that changes can't be made backward compatible, then it's OK for because it seems that you know what you are doing.  Maybe changing things in backward compatible way is the right thing to do, because it seems very few people are using camlp5 right now and we will not make a lot of people angry.

I managed to fix my code. All 3 issues were about this option introduction. https://github.com/Kakadu/GT/commit/df842ac011626689730c718d659eaf5136ba5df4

I think that after changing CHANGELOG file it's OK to close this issue.

**Comment by chetmurthy** [comment]
Oh, I hadn't realized that the code snippet you showed me was the actual problematic code (I assumed it was a simplified example).  I thought you were doing things like
```
<:str_item< module $list:lsme$ >>
```
with lists `lsme` of length greater than one, or that got passed as arguments.  But your diff shows that you're only using them in more-normal ways, so in fact, I think you can get something that is completely backward-compatible.  I tested the following patch by building under ocaml-4.09.0+camlp5-7.10 and ocaml-4.10.0-rc1+camlp5-7.11, and it built both times.  I cannot figure out how to coax ocamlbuild to give me the actual commands, so I can modify them and look at the raw ocaml source to verify that things are correct, but I think this should work.

If you could tell me how to get the raw commands, I would be happy to send you a PR with changes that build and are verified against both versions of camlp5.

```
diff --git a/camlp5/Camlp5Helpers.ml b/camlp5/Camlp5Helpers.ml
index 07a7bd1..ffab939 100644
--- a/camlp5/Camlp5Helpers.ml
+++ b/camlp5/Camlp5Helpers.ml
@@ -441,7 +441,7 @@ module Str = struct
 
   let module_ ~loc name me =
     let lsme = [ (VaVal (Some (VaVal name)), me)] in
-    <:str_item< module $list:lsme$ >>
+    <:str_item< module $uid:name$ = $me$ >>
 
   let modtype ~loc (_,name,topt) =
     match topt with
@@ -555,7 +555,7 @@ module Sig = struct
     let mt1 = <:module_type< sig $list:sigs_arg$ end >> in
     let mt2 = <:module_type< sig $list:sigs_r$ end >> in
     let mt  = <:module_type< functor ($param$ : $mt1$) -> $mt2$ >> in
-    <:sig_item< module $list:[ (VaVal (Some (VaVal name)), mt) ]$ >>
+    <:sig_item< module $uid:name$ = $mt$ >>
 
 
   let simple_gadt (* : loc:loc -> name:string -> params_count:int -> (string * Typ.t) list -> t *) =
@@ -594,7 +594,7 @@ module Sig = struct
     <:sig_item< type $list:[td]$ >>
 
   let module_ ~loc (_,name,mtyp) =
-    <:sig_item< module $list:[(VaVal (Some (VaVal name)),mtyp)]$ >>
+    <:sig_item< module $uid:name$ : $mtyp$ >>
 
   let modtype ~loc (_loc,s,mt_opt) =
     let mt =

```

**Comment by chetmurthy** [comment]
Oof, I figured out how to build your project; I'll re-submit a comment once I get it working and backward-compatible.

**Comment by Kakadu** [comment]
````diff
-    <:sig_item< module $list:[ (VaVal (Some (VaVal name)), mt) ]$ >>
+    <:sig_item< module $uid:name$ = $mt$ >>
````
I actually thought that we can't use quotation in this manner. I looked at `chapter 5.4.1/module` of [manual](https://camlp5.github.io/doc/htmlc/ast_strict.html#b:modules---) and thought that using quotations as you do is not possible. Is it me being stupid or shortcoming of manual?

**Comment by chetmurthy** [comment]
OK, I tried a bit, and found that there are dependencies on ppxlib, that don't compile under ocaml 4.10.0.  I could fix them, but ....
(1) maybe you can tell me how to work around these problems so I can build GT under 4.10.0 ?
(2) I extracted the code that was broken by camlp5 7.11 into a separate file, added an MLI (to ensure that type-signatures didn't change), applied the changes I suggested above, and then verified that everything built under both 7.10 and 7.11.  Here's the file:
```
  let module_ ~loc name me =
    <:str_item< module $uid:name$ = $mexp:me$ >>


  let functor1 ~loc name ~param sigs_arg sigs_r =
    let mt1 = <:module_type< sig $list:sigs_arg$ end >> in
    let mt2 = <:module_type< sig $list:sigs_r$ end >> in
    let mt  = <:module_type< functor ($param$ : $mt1$) -> $mt2$ >> in
    <:sig_item< module $uid:name$ : $mtyp:mt$ >>


  let module2_ ~loc (_,name,mtyp) =
    <:sig_item< module $uid:name$ : $mtyp:mtyp$ >>
```
If you could suggest to me how to get GT to build under 4.10.0, I would be happy to send you a PR, so you don't have to integrate these changes manually.

**Comment by Kakadu** [comment]
I applied your patch and it seems that it is good. Many thanks!

**Comment by Kakadu** [comment]
I'm OKay to close this.
