### ISSUE TITLE
OCaml 4.11 support

### ISSUE THREAD

**Issue by rwmjones** [camlp5/camlp5#58]
camlp5 doesn't compile on OCaml 4.11 at the moment:
```
+ ./configure
Sorry: the compatibility with ocaml version "4.11.0+dev0-2019-10-18"
is not yet implemented. Please report.
Information: directory ocaml_stuff/4.11.0 is missing.
Configuration failed.
```
https://koji.fedoraproject.org/koji/buildinfo?buildID=1495066

**Comment by chetmurthy** [comment]
oh, nice.  I'll get right on it.  Should be ale to provide it on a branch soonest,

**Comment by chetmurthy** [comment]
Richard, I have a "works up to bootstrapping" version of camlp5 for 4.11.0.  But there are a bunch of syntax changes that will need to be worked-thru, including unit-tests, etc.  As with the 7.11 release (4.10.0 compatibility, but no support for (e.g.) attributes/extensions), I'd like to defer the full syntax support until I release 8.00, which should be within the next three months.

Would that work for you?

As always, I'll verify that this all works with all the previous versions of ocaml that I can install&test using opam.  So: almost everything >= 4.00.0.

**Comment by chetmurthy** [comment]
Could you try the branch pre-7.12 and let me know if works for you?  Should work with 4.10.0, 4.11.0, and all versions down to 4.00.0.

**Comment by rwmjones** [comment]
Yes, I have OCaml 4.11 prerelease on my Fedora Rawhide system.  What patch / branch should I try?

**Comment by rwmjones** [comment]
`./configure && make` works fine.  `make -C test -j1 all` prints some warnings but doesn't have any errors.  Is there anything else you would want me to try?

**Comment by chetmurthy** [comment]
That's about it.  It should mean it pretty much works, though there aren't any unit-tests of any worth in that release of camlp5.  I'm about to upgrade my pre-8.00 branch to 4.11.0 support, and there, there are a -ton- of unit-tests (as well as a bunch of development I'm doing on a ton of PPX rewriters), so if I find any bugs that I can backport fixes for, I will certainly do so.

May I ask: do you use camlp5  ?  And if so, what for?  If you can point me at projects that you use, that depend on camlp5, I can ensure that they continue to work with 8.00.0 when it comes out.

**Comment by chetmurthy** [comment]
I felt I should repeat: there's new syntax in ocaml 4.11.0 that camlp5 does not yet support (heh, I couldn't exactly get that done in the hour-or-so it took to get this little patch out). I'll put that into the 8.00.0 branch soon.  If you need syntax support for these new features, let me know, and I can make a pre-release version of 8.00.0 available sooner.

**Comment by rwmjones** [comment]
I use camlp5 occasionally, but my interest here is for Fedora where a large number of packages depend on it indirectly.  The direct dependencies in Fedora are: `gappalib-coq`, `haxe`, `ocaml-lablgtk3` and `why3`.  But that means we cannot compile the whole Coq stack and Frama-C.

**Comment by rwmjones** [comment]
Thanks, now built in Fedora:
https://koji.fedoraproject.org/koji/taskinfo?taskID=44093994
