### ISSUE TITLE
configure should ignore/warn not error on unknown options

### ISSUE THREAD

**Issue by rwmjones** [camlp5/camlp5#59]
In Fedora we'd prefer to use our `%configure` macro.  This macro assumes an autotools-ish configure.  In any case it uses a lot of options that overlap with the camlp5 configure script but includes some extra stuff:

```
+ ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu \
--program-prefix= --disable-dependency-tracking --prefix=/usr \
--exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc \
--datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 \
--libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib \
--mandir=/usr/share/man --infodir=/usr/share/info
Unknown option "--build=x86_64-redhat-linux-gnu".
```

This would work better if either you use autotools, or failing that you just ignore options that you don't care about.

**Comment by rwmjones** [comment]
Also the configure script is kind of weird because it has an `--libdir` option, but that causes it to create empty directories `$libdir/camlp5` and `$libdir/ocaml`, and then it puts files in:
```
./usr/lib64/camlp5
./usr/lib64/ocaml/topfind.camlp5
```

**Comment by roglo** [comment]
I am against using that. It adds a version dependency for something not
really essential. 

Daniel 

Le 04/05/2020 18:27, rwmjones a écrit :

> In Fedora we'd prefer to use our %configure macro. This macro assumes an autotools-ish configure. In any case it uses a lot of options that overlap with the camlp5 configure script but include some extra stuff:
> 
> + ./configure --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info
> Unknown option "--build=x86_64-redhat-linux-gnu".
> 
> This would work better if either you use autotools, or failing that you just ignore options that you don't care about. 
> 
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1] https://github.com/camlp5/camlp5/issues/59
[2]

**Comment by rwmjones** [comment]
> I am against using that.

Against using what?

**Comment by roglo** [comment]
Using autotools. 

Le 04/05/2020 18:33, rwmjones a écrit :

>> I am against using that.
> 
> Against using what? 
> 
> --
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].

 

Links:
------
[1] https://github.com/camlp5/camlp5/issues/59#issuecomment-623570409
[2]

**Comment by rwmjones** [comment]
Sure, autotools sucks, although it doesn't add any dependencies because it carries around the generated shell script in the tarball (one reason it sucks).

However the other option would be to ignore --flags which you don't understand.
