### ISSUE TITLE
incorrect constraints in opam file

### ISSUE THREAD

**Issue by olafhering** [camlp5/camlp5#60]
As of version 7.12 the opam file has `ocaml < 4.12`.
But in fact this has to be `ocaml <= 4.11.0`, simply because it does not seem to understand ocaml `4.11.1`.

**Comment by chetmurthy** [comment]
[Hi, I replied issue #61 about this]
I'll figure out how to prevent this from happening every time there's an ocaml bugfix release.

**Comment by chetmurthy** [comment]
If you could switch to that issue (#61) to comment on this problem (and close this issue), I'd appreciate it.  Just to minimize the bureaucracy.

**Comment by chetmurthy** [comment]
published a fix, you can also checkout from camlp5/camlp5#master.  Thank you for finding this and letting me know!
