### ISSUE TITLE
Assertion failed on 4.09

### ISSUE THREAD

**Issue by Kakadu** [camlp5/camlp5#67]
compilation of GT.0.3.0 doesn't work because of this line https://github.com/camlp5/camlp5/blob/master/lib/versdep.ml#L206

```ocaml
IFDEF OCAML_VERSION < OCAML_4_10_0 THEN
value ocaml_attribute_implem _ _ _ = assert False ;
```

Discovered while hacking https://github.com/ocaml/opam-repository/pull/17285

**Comment by chetmurthy** [comment]
Yes, none of the new syntax (OK, it's not new in OCaml, but new support in Camlp5) is supported for OCaml < 4.10).  The work of back-porting it to earlier versions of OCaml would be too great.

**Comment by Kakadu** [comment]
So, the right decision will be to constraint GT with ocaml >= 4.10?

Also, is it a good idea to add `failwith "never going to be implemented"` instead of `Assert False`?

**Comment by chetmurthy** [comment]
Heh, that's a good idea.  I'll do that.

**Comment by Kakadu** [comment]
It seems that this PR is almost ready to close.

Almost random question: @chetmurthy , why your commit messages include lines that are commented using `#` and should not appear in commit messages? Do you use any fancy unicode analogue of `#` or something like that?

**Comment by chetmurthy** [comment]
Those are comments inserted by the Emacs "magit" package, which I use to  interact with git.  I haven't found them problematic, so I didn't go looking for a way to disable them.

**Comment by chetmurthy** [comment]
closing.

**Comment by chetmurthy** [comment]
Oops, yeah, I need to address this.  Sorry, buddy.  I need to fix this.

**Comment by Kakadu** [comment]
I have moved to new versions of OCaml. I'm OKay if you will close  this...
