### ISSUE TITLE
Even in transitional mode, pa_reloc.ml reverts to strict mode

### ISSUE THREAD

**Issue by girving** [camlp5/camlp5#7]
I'm trying to get HOL Light running on a machine with ocaml 4.04, camlp5 6.17 transitional:

    emmy:~% ocamlc -v
    The OCaml compiler, version 4.04.0
    Standard library directory: /usr/local/lib/ocaml
    emmy:~% camlp5 -v
    Camlp5 version 6.17 (ocaml 4.04.0)
    emmy:~% camlp5 -pmode
    transitional

Unfortunately, I get a bunch of errors like

    File "pa_j.ml", line 117, characters 71-73:
    Error: This expression has type (string * MLast.ctyp) list
           but an expression was expected of type
             ('a * MLast.ctyp) list Ploc.vala
    make: *** [pa_j.cmo] Error 2

caused by camlp5 trying to detect whether strict mode is by checking for the `STRICT` preprocessor define (https://github.com/girving/hol-light/blob/native/pa_j_tweak.ml#L43).  Unfortunately, `pa_reloc.ml` turns on strict mode before this happens, which seems to turn on the `STRICT` macro as well.  Thus HOL Light thinks that strict mode is on, which is wrong for a good chunk of the camlp5 API.

I'm still trying to work around this on the HOL Light side, but I thought I'd report it here as well since mixing camlp5 between strict and transitional seems like a bug.

**Comment by girving** [comment]
Here's the problematic line of `pa_reloc.ml`: https://github.com/camlp5/camlp5/blob/2b07889b208b29ef447682a24355bd05c43edd28/etc/pa_reloc.ml#L11

**Comment by roglo** [comment]
I am not sure I understand the problem well. I have not been working on Camlp5 for several years and I don't remember. But while looking at my code, I think that pa_reloc should not have an influence to users programs. It is only used to rebuild (bootstrap) the source file main/reloc.ml when I make changes in the Camlp5 AST (main/mLast.mli). I use for that "make compare_reloc" and "make bootstrap_reloc" in the directory main.

**Comment by girving** [comment]
I'm not sure if it's intended usage, but HOL Light imports `pa_reloc` directly: https://github.com/girving/hol-light/blob/master/pa_j_3.1x_6.xx.ml#L11

**Comment by roglo** [comment]
Ok. While compiling hol-light which I cloned from github, I get another error at another line:
File "pa_j.ml", line 1918, characters 35-43:
While expanding quotation "str_item":
Parse error: antiquot "_" or antiquot "" or [ident] expected after 'type' (in
  [str_item])
File "pa_j.ml", line 1:

This is due to the fact that camlp5 file etc/pa_o.ml has been copied in hol-light sources. But there have been some changes in etc/pa_o.ml since that time, and they should be copied. See etc/pa_o.ml in present camlp5 sources to see how is now the equivalent code.

**Comment by girving** [comment]
@roglo HOL Light requires a patch to build even if strict mode: https://github.com/girving/hol-light/commit/f80524bad61fd6f6facaa42153b2e29d1eab4658.  I'll take a look at `etc/pa_o.ml` and try to replicate the rest of the changes to see if that helps.
