### ISSUE TITLE
OCaml 4.10.2 build issue

### ISSUE THREAD

**Issue by chenrui333** [camlp5/camlp5#71]
👋  it looks like camlp5 does not build with ocaml 4.10.2 yet.
```
==> ./configure --prefix /usr/local/Cellar/camlp5/7.13_1 --mandir /usr/local/Cellar/camlp5/7.13_1/share/man

Sorry: the compatibility with ocaml version "4.10.2"
is not yet implemented. Please report.

Information: directory ocaml_stuff/4.10.2 is missing.
```

**Comment by chetmurthy** [comment]
I'm working on compatibility upgrades for the 7.xx branch right now.  8.xx branch already done.  Neither is released, but that'll happen soon too.  Will post back to this issue when it's committed so you can use it, and at some point after that, it'll get released.

**Comment by chetmurthy** [comment]
tag rel714 is pushed and PR submitted for opam release.  Closing.

**Comment by chenrui333** [comment]
Thanks @chetmurthy!
