### ISSUE TITLE
latest release tag still points to rel711

### ISSUE THREAD

**Issue by chenrui333** [camlp5/camlp5#73]
👋  it looks like latest tag still points rel711, I wonder if it is possible to mark rel800 as the latest release tag to avoid confusion. Thanks!

---

![image](https://user-images.githubusercontent.com/1580956/103470779-c00b1a00-4d44-11eb-9f66-cfe90e0cc62c.png)

**Comment by chetmurthy** [comment]
Thanks for asking!  I did not know how to do this, and didn't bother to find out.  It's actually trivial, so I'll do it from now on!

**Comment by chenrui333** [comment]
yeah, it is pretty trivial, thanks for doing that. 👍
