### ISSUE TITLE
`pr_o` printing issue about `(+)`: missing parenthesis

### ISSUE THREAD

**Issue by Kakadu** [camlp5/camlp5#74]
Compilation failure 

    echo 'let _ = Stdlib.(+)' > percent.ml && \
      ocamlc -c -pp 'camlp5o pa_o.cmo pr_o.cmo' -dsource percent.ml

    File "/tmp/ocamlppd7b057", line 2, characters 0-0:
    Error: Syntax error

Printed by pr_o (parenthesis are missing)

    echo 'let _ = Stdlib.(+)' > percent.ml && \
       camlp5o pa_o.cmo pr_o.cmo percent.ml  

    let _ = Stdlib.+

Right way of printing:

    echo 'let _ = Stdlib.(+)' > percent.ml && \
      ocamlc -c  -dsource percent.ml        

    let _ = Stdlib.(+)

   @chetmurthy ?

**Comment by chetmurthy** [comment]
Oops.  oversight.  Fixed in 6c9b34f8 with unit-test.

**Comment by Kakadu** [comment]
Good!
Also you could write 'Fix #74' in commit message to make this issue closed automatically
