### ISSUE TITLE
Use `{|` as a normal token?

### ISSUE THREAD

**Issue by LdBeth** [camlp5/camlp5#79]
I guess that although `{|` is now used by OCaml as raw string syntax, it should still possible to use it as a normal token when `simplest_raw_strings.val := False`, which is implied by the docstring:
```
   (** When False (default), the next call to [Plexer.gmake ()] returns a
       lexer where {|...|} is not a valid raw-string.  Setting it to True
       will allow such strings to be valid raw-strings, while checking for
       and throwing an error if "{|" and "|}" are specified  as keywords. *)
```

However with CamlP5 8.00 release, when processing a form like

```
prim rewriteAxiom1 {| intro [] |} : (* line  89 *)
   sequent { <H> >- Perv!"rewrite"{'a; 'a} } = it
```

it gives error
```
----------------------------------
Parse error in entry [nonwordterm], rule:
  [ "{"; word_or_string*; "="; aterm*; LIST0 rcrdterm*; "}"
  | "{"; word_or_string*; ":"; aterm*; ";"; LIST0 recordterm* SEP ";"; "}"
  | "{"; word_or_string*; ":"; aterm*; "}"
  | "{"; word_or_string*; ":"; aterm*; "|"; aterm*; "}"
  | "{"; word_or_string*; "|"; aterm*; "}" ]
----------------------------------

File "base_rewrite.ml", line 89, characters 21-22:
Parse error: [word_or_string] expected after '{' (in [nonwordterm])
- build theories/meta/base base_operator.ppo
```

While the grammar is

```
| "prim"; name = LIDENT; res = optresources; params = optarglist; ":"; body = rule_body
optresources:
      [[ ores = OPT updresources -> ...
updresource:
      [[ flag = opt_pvt_flag; e = expr LEVEL "expr1" -> ...
updresources:
      [[ "{|"; res = LIST1 updresource SEP ";" ; "|}" -> ...
...
optarglist:
      [[ args = LIST0 singleterm -> ...
...
singleterm:
         [ [ op = opname_list -> ...
          | "sequent" NONA
            [ arg = SELF; "{|"; (hyps, concl) = sequent_body; "|}" -> ...
          | [ t = nonwordterm -> ...
```
No idea how this happens, but why CamlP5 try to match `optarglist` before try `optresources`.

**Comment by LdBeth** [comment]
In addition, if change to `[|` & `|]`or `{<` `>}` accordingly it can be recognized.

could this related to that `|` can be matched by `UIDENT` etc?

```
word_or_string:
         [[ name = UIDENT ->
             name
           | name = LIDENT ->
             name
           | name = STRING ->
             Token.eval_string loc name ...
```

**Comment by LdBeth** [comment]
a little more detail, using `"{"; "|";` can indeed match the form, indicates the lexer treats `{|` as two tokens instead of one somehow.

**Comment by chetmurthy** [comment]
Whups!  That's a bug!  I'll fix it and report back.

**Comment by chetmurthy** [comment]
OK, camlp5/camlp5 master (e0fa35f232c50a36c355a346a030310f5133d6a1) should fix this bug.  It'll go out in the next bigfix release.

**Comment by LdBeth** [comment]
Thank you, tested with master branch and it works now.

**Comment by chetmurthy** [comment]
Thank you for taking the time to report this, and to test the fix!  I'll plan on a bugfix release in the next month -- hope that that's soon enough (if not, let me know, and I'll move it up -- the only reason I would wait, is in hope that other bugs also crop up, so I can fix those too).

Closing.
