### ISSUE TITLE
Stream module moving from OCaml stdlib to camlp-stream library

### ISSUE THREAD

**Issue by xavierleroy** [camlp5/camlp5#81]
Camlp5-generated parsers and printers rely on the Stream module from the OCaml standard library.  Some parsers also use the Genlex module as lexer.

The core OCaml development team is planning to remove the Stream and Genlex modules from the standard library, after a few releases where these modules will be marked as deprecated (https://github.com/ocaml/ocaml/pull/10482).

In parallel, a new library [camlp-streams ](https://github.com/ocaml/camlp-streams) providing the Stream and Genlex modules is already available and packaged in OPAM.

For a smooth transition, Camlp5 needs to be modified sooner than later to link the preprocessed code with the camlp-streams library.  It should suffice to change the META file to require the `camlp_streams` package.  OPAM dependencies will have to be updated as well.

Thanks for your attention.

**Comment by xavierleroy** [comment]
Last call for feedback before https://github.com/ocaml/ocaml/pull/10482 is merged.

**Comment by chetmurthy** [comment]
Sorry: I should have replied.  I'll ensure that when the next bugfix release of camlp5 (for Ocaml 4.13.0) comes out, it will switch to using camlp-streams.

**Comment by Kakadu** [comment]
@chetmurthy Gentle ping, could this be closed?

**Comment by chetmurthy** [comment]
Good point.  I'll close this, since the last couple of releases of camlp5 should be all-switched-over.
